# Generated by Django 4.2.5 on 2023-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('spotify_id', models.CharField()),
                ('album', models.CharField()),
                ('release_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
